### ISSUE TITLE
写的这是啥破玩意，删除了吧。别丢人了

### ISSUE THREAD

**Issue by renjiali** [ivy-design/ivy-design-wc#29]
你这破玩意就是在浪费人家github和npm存储空间

**Comment by GuoJikun** [comment]
> 你这破玩意就是在浪费人家github和npm存储空间

照你这么说你就不该创建账号。

**Comment by renjiali** [comment]
> > 你这破玩意就是在浪费人家github和npm存储空间
> 
> 照你这么说你就不该创建账号。

对，你就不该建立这个账号
